### ISSUE TITLE
database dependencies

### ISSUE THREAD

**Issue by drewda** [dobtco/formbuilder-rb#1]
@adamjacobbecker, are you building this library with just Postgres in mind? Or do you plan to support other databases behind ActiveRecord?

Just asking since I see mention of an `hstore` column.

**Comment by ajb** [comment]
Hmm... so hstore lets us do a lot of cool things that wouldn't otherwise be possible, like sorting on the response columns. Thanks for bringing this up though -- I'll add a note in the readme. It shouldn't be too hard to add support for a serialized text field instead, but you'll lose a bunch of functionality.

**Comment by drewda** [comment]
Having implemented this kind of forms, fields, and, responses schema with
only tables and relations a few times in the past, I definitely see the
power of an hstore column to consolidate a lot of complexity. (If only the
folks at Amazon would also--and add Postgres support to AWS RDS.) Anyways,
support for a serialized text column sounds like a decent bone to throw to
MySQL users at some point.

**Comment by lustercr** [comment]
has anyone implemented this  serialized field customization for allowing mysql support ? i would like to get a clue on this

Thanks

**Comment by JakeAustwick** [comment]
@lustercr It hasn't been implemented as of yet, although the above issue of Amazon RDS not supporting Postgres is no longer true.

**Comment by RailsCod3rFuture** [comment]
Has anyone implemented MySQL support as of yet?
